### ISSUE TITLE
VS2013的XAML编辑器有问题

### ISSUE THREAD

**Issue by lkytal** [theoractice/VSCustomize#1]
由你制作的VS2013硬盘版很实用, 感谢.
不过其XAML编辑器无法进入设计界面, 是什么原因呢?
顺便, 有无vs2105绿色版的计划, 不胜期待.

**Comment by theoractice** [comment]
估计是你那个版本很久没有更新了。需要最新版可以给我发邮件。
vs2105肯定是没有的。我跟微软二者之中至少有一个撑不到那个时候。
至于vs2015绿色版，会在微软停止更新vs2015之后开始制作。到那个时候你估计又会期盼vs2016了吧。打破这种循环唯有自己动手:)

**Comment by lkytal** [comment]
在下邮箱lkytal@126.com, 希望能发一份新版的地址, 谢谢.
自己有过些尝试, 不过不太成功. vs2015似乎已经不会有下一个update了, 在下就惭愧的期待一下了.

**Comment by theoractice** [comment]
一般我会等半年。update3是6月发的，所以这次大概到明年年初做吧。
