### ISSUE TITLE
vs2017便携版wdk如何集成呢

### ISSUE THREAD

**Issue by ddkwork** [theoractice/VSCustomize#4]
vs2017便携版wdk如何集成呢

**Comment by theoractice** [comment]
2017版是当时尝鲜做的，已经删除，不建议使用。

**Comment by ddkwork** [comment]
> 2017年版是当时尝鲜做的，已经删除，不建议使用。
虽然如此，还是很期待2017的便携版更新，现在发布的这个不能安装wdk拓展

**Comment by theoractice** [comment]
> > 2017年版是当时尝鲜做的，已经删除，不建议使用。
> > 虽然如此，还是很期待2017的便携版更新，现在发布的这个不能安装wdk拓展

其实2017现在安装很快，而且随时更新，还算是挺方便的。个人觉得做便携版的作用没有以前那些版本大了。
