### ISSUE TITLE
2019新版做个精简版吧

### ISSUE THREAD

**Issue by sdragonx** [theoractice/VSCustomize#7]
如题。

**Comment by theoractice** [comment]
不考虑了。一是因为vs2019更新很频繁，二是它自己就可以选择模块安装，而且速度也不慢，做绿色版的意义不是很大了。你想自己做的话可以看我的教程。

**Comment by sdragonx** [comment]
每次重做系统很繁琐，绿色安装比较方便，自己做有点不太会。

**Comment by theoractice** [comment]
哪里不会来问我。

**Comment by sdragonx** [comment]
2022要出来了，2019估计会停止更新。做最后一版的就行。

**Comment by theoractice** [comment]
如上，不再回复。
