### ISSUE TITLE
请问能把制作Install.exe打包前的文件及全部iss脚本发一下吗？

### ISSUE THREAD

**Issue by ostaith** [theoractice/VSCustomize#8]
你好，非常感谢你做的VS2017精简版。
但是最近在安装某些python包的时候，遇到这样的问题：`error: Microsoft Visual C++ 14.0 or greater is required`，网上说要安装`vs_BuildTools`，我在想，我已经安装了VS2017精简版，怎么python识别不了？
后来研究了下，发现只要把[vswhere 2.7.1](https://github.com/microsoft/vswhere/releases/tag/2.7.1)拷贝到`%ProgramFiles%\Microsoft Visual Studio\Installer`，python就可以识别了。因此想把`vswhere`重新打包到`Install.exe`。
但是要重新打包，没有打包前的文件，
1. 使用Innosetup解压工具解压，又担心解压出来的文件与你的原始文件不一致，能不能把你打包前的原始文件压缩下上传到百度网盘？
2. 我用解压工具解开的文件结构如下，
![image](https://user-images.githubusercontent.com/34862369/161675439-84afd88f-679f-4816-b454-e20620329d18.png)
感觉和你的原始文件目标结构不一致，
![image](https://user-images.githubusercontent.com/34862369/161675586-5c57b12c-7975-4516-a9b1-1c29a0debc40.png)
你的脚本里有`System32`和`System64`这两个目录，但是解开后的目录里没有。
3. 脚本文件里好像有些东西没有，比如这个页面，不知道是不是脚本实现的？
![image](https://user-images.githubusercontent.com/34862369/161676812-7b2296cc-08fa-47a8-a758-62a87e270635.png)
4. 你打包的安装文件，最后有生成快捷链接，但是在你发的`installer.iss`脚本里，没有看到这部分的内容
5. 另外请教下，你的`installer.iss`脚本里，`{cf}`、`{commonappdata}`、`{src}`、`{cmd}`这些是什么含义？是系统预定义的变量吗？其它几个看起来像是预定义变量，但是`{src}`好像不是，能不能简单解释下？
6. 不知道能不能简单解释下你开发的lnk2iss、pathman、PortableHelper、RegIssPostProc、VSC.Shared这几个工具的作用？重新打包`Install.exe`要不要用到这些工具？

**Comment by ostaith** [comment]
实际上写了这么多，一句话描述下就是：希望`VS2017精简版`能解决Python无法识别的bug。
bug的解决方法就是我上面给的，可以把`vswhere`打包进`Install.exe`，并且解压到`%ProgramFiles%\Microsoft Visual Studio\Installer`。
如果你能重新打包`Install.exe`，然后重新发布`VS2017精简版`也可以。或者在这里把所有的素材发布下，并且指导下，以后遇到问题，网友们可以自行打包`Install.exe`解决，那就更好。非常感谢！

**Comment by ostaith** [comment]
那几个预定义变量的含义刚刚网上[找到解释](https://www.cnblogs.com/itech/archive/2011/02/27/1966486.html)了，{src}就是安装文件所在的目录。这点不用再解答了，谢谢！

**Comment by theoractice** [comment]
那个vs2017硬盘版是微软刚刚发布vs2017的时候我做着玩的，当时的vs2017初版本身就有很多bug，完全不建议使用，我也早就把这个版本从我自己的网盘分享链接里删除了，你找到的版本可能是其他人共享的。目前最稳定并且最新的版本是vs2015的硬盘版。

从vs2017开始由于微软自己做了模块化的安装器，安装速度、稳定性和方便程度提高了不少，所以vs硬盘版这个事情后来我就没有再做过了。**目前我对制作vs2017及以后版本的vs硬盘版没有兴趣，也认为没有必要。**

我写过一个如何制作vs硬盘版的教程，见[http://theoractice.github.io/](http://theoractice.github.io/)。制作中需要的所有工具都打成压缩包放在本repo的[IssBackup](https://github.com/theoractice/VSCustomize/tree/master/IssBackup)目录下了。当然你应该已经看到了。

接下来回答你的问题：
1.因为完全不建议使用我当年尝鲜做的vs2017硬盘版，所以如果真的有需求，建议你按照我的教程从头开始重新制作。这样的话安装文件也需要你自己按照我的教程去重新提取。
2.这是因为为了兼容32位和64位系统，需要提取不同版本的安装文件。当然现在已经是2022年了，你自己重做的话完全可以只提取64位系统的安装文件。
3.这是innosetup的自带功能。
4.快捷方式链接的安装脚本是用lnk2iss工具自动生成的。
5.如你所说，可参考innosetup的自带帮助文档。
6.lnk2iss--生成快捷方式链接的安装脚本；pathman--批量添加/删除环境变量；PortableHelper--把所有需要的vs安装文件拷贝到单独的文件夹；RegIssPostProc--本repo里的压缩包里还有一个Converter.exe，制作时先用Converter把注册表文件转换为注册表安装脚本，然后再用RegIssPostProc对转换好的脚本进行后处理（教程里提到过这里的坑多得令人发指）；VSC.Shared--各个工具公用的库。总之只要认真读过我的教程，就会发现这里面所有的工具其实都在教程里提到了（虽然没有具体指出名字）。
